scrolling:
  multiplier: 5

font:
  normal:
    family: Terminess Nerd Font
    style: Regular

  bold:
    family: Terminess Nerd Font
    style: Bold

  italic:
    family: Terminess Nerd Font
    style: Italic

  bold_italic:
    family: Terminess Nerd Font
    style: Bold Italic

  size: 12
  offset:
      x: 0
      y: 0

colors:
  primary:
    background: '#181818'
    foreground: '#d8d8d8'

  cursor:
    text: '#d8d8d8'
    cursor: '#d8d8d8'

  normal:
    black:   '#181818'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#d8d8d8'

  bright:
    black:   '#585858'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#f8f8f8'

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: K,   mods: Control|Shift, action: ScrollPageUp }
  - { key: J,   mods: Control|Shift, action: ScrollPageDown }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
