scrolling:
  multiplier: 5

font:
  normal:
    family: Terminus
    style: Regular

  bold:
    family: Terminus
    style: Bold
    family: Terminus

  italic:
    family: Terminus
    style: Italic
    family: Terminus

  bold_italic:
    family: Terminus
    style: Bold Italic
    family: Terminus

  size: 14
  offset:
      x: 0
      y: 0



# Colors (Hyper)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#ffffff'
  cursor:
    text: '#F81CE5'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#fe0100'
    green:   '#33ff00'
    yellow:  '#feff00'
    blue:    '#0066ff'
    magenta: '#cc00ff'
    cyan:    '#00ffff'
    white:   '#d0d0d0'

  # Bright colors
  bright:
    black:   '#808080'
    red:     '#fe0100'
    green:   '#33ff00'
    yellow:  '#feff00'
    blue:    '#0066ff'
    magenta: '#cc00ff'
    cyan:    '#00ffff'
    white:   '#FFFFFF'



key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: K,   mods: Control|Shift, action: ScrollPageUp }
  - { key: J,   mods: Control|Shift, action: ScrollPageDown }

