scrolling:
  multiplier: 5

font:
  normal:
    family: Misc Tamsyn
    style: Regular

  bold:
    family: Misc Tamsyn
    style: Bold
    family: Misc Tamsyn

  italic:
    family: Misc Tamsyn
    style: Italic
    family: Misc Tamsyn

  bold_italic:
    family: Misc Tamsyn
    style: Bold Italic
    family: Misc Tamsyn

  size: 14
  offset:
      x: 0
      y: 0


# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#000000'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: K,   mods: Control|Shift, action: ScrollPageUp }
  - { key: J,   mods: Control|Shift, action: ScrollPageDown }

